### ISSUE TITLE
Ambassador operator seems to overwrite changes made to running configurations

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador-operator#53]
Ambassador yaml installed via the operator seems to refuse to be changed with `kubectl edit`.

**Reproduce:**

1. Run the latest minikube: `minikube start`

2. Install ambassador via operator: `minikube addons enable ambassador`

3. Try to change the ambassador image with `kubectl edit deploy ambassador -n ambassador`

4. See that nothing ends up changing because the changes you make with `kubectl edit` get overwritten

**Comment by inercia** [comment]
This is the expected behavior: users cannot edit the `ambassacdor` `Deployment`: it will be overwritten by the Operator. Any change should be done in the `AmbassadorInstallation`. The Operator is notified when a resource has changed, so if users modify the `deployment`, the Operator will immediately wake up and overwrite it.
